version: '2'
services:
    fullstackdev_2017a-app:
        image: fullstackdev_2017a
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fullstackdev_2017a-mysql:3306/fullstackdev_2017a?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fullstackdev_2017a-mysql:
        extends:
            file: mysql.yml
            service: fullstackdev_2017a-mysql
